"use client";

import Link from "next/link";
import { useRoadmap } from "@/hooks/use-roadmap";
import { useRoadmapProgress } from "@/hooks/use-roadmap-progress";
import { fixMojibake } from "@/lib/utils";
import { ROUTES } from "@/lib/constants";
import { PageHeader } from "@/components/shared/page-header";
import { LoadingSpinner } from "@/components/shared/loading-spinner";
import { EmptyState } from "@/components/shared/empty-state";
import { RoadmapProgressBar } from "@/components/roadmap/roadmap-progress-bar";
import { PhaseCard, type PhaseStatus } from "@/components/roadmap/phase-card";
import type { RoadmapPhaseDetail } from "@/types/roadmap.types";

function deriveStatuses(
  phases: RoadmapPhaseDetail[],
  doneInPhase: (phaseId: string, count: number) => number,
): Record<string, PhaseStatus> {
  const result: Record<string, PhaseStatus> = {};
  let foundCurrent = false;
  for (const phase of phases) {
    const total = phase.milestones.length;
    const done = doneInPhase(phase.id, total);
    if (total > 0 && done >= total) {
      result[phase.id] = "done";
    } else if (!foundCurrent) {
      result[phase.id] = "current";
      foundCurrent = true;
    } else {
      result[phase.id] = "future";
    }
  }
  return result;
}

export default function RoadmapPage() {
  const { roadmap, isLoading, isEmpty, isError } = useRoadmap();
  const { doneInPhase } = useRoadmapProgress(roadmap?.id ?? null);

  if (isLoading) {
    return (
      <div className="mx-auto max-w-[1100px] px-7 py-7">
        <LoadingSpinner fullPage label="Loading your roadmap…" />
      </div>
    );
  }

  if (isError) {
    return (
      <div className="mx-auto max-w-[1100px] px-7 py-7">
        <EmptyState
          title="Couldn't load your roadmap"
          description="There was a problem fetching your roadmap. Please refresh and try again."
        />
      </div>
    );
  }

  if (isEmpty || !roadmap) {
    return (
      <div className="mx-auto max-w-[1100px] px-7 py-7">
        <PageHeader
          eyebrow="Your plan"
          title="Career Roadmap"
          description="A week-by-week plan toward your target role, generated by your AI career coach."
        />
        <EmptyState
          title="No roadmap yet"
          description="Tell us about your goal and we'll build a personalised, phase-by-phase plan to get you there."
          action={
            <Link
              href={ROUTES.onboarding}
              className="inline-flex items-center rounded-[7px] bg-ink px-4 py-2 text-[13px] font-medium text-bg transition-colors duration-150 hover:bg-green-2"
            >
              Generate my roadmap
            </Link>
          }
        />
      </div>
    );
  }

  const phases = [...roadmap.phases].sort((a, b) => a.order - b.order);
  const statuses = deriveStatuses(phases, doneInPhase);

  const totalMilestones = phases.reduce((s, p) => s + p.milestones.length, 0);
  const completedMilestones = phases.reduce(
    (s, p) => s + doneInPhase(p.id, p.milestones.length),
    0,
  );
  const overallPct =
    totalMilestones > 0 ? (completedMilestones / totalMilestones) * 100 : 0;
  const totalWeeks = phases.reduce((s, p) => s + p.durationWeeks, 0);

  return (
    <div className="mx-auto max-w-[1100px] px-7 pb-24 pt-7">
      <PageHeader
        eyebrow="Your plan"
        title="Career Roadmap"
        description={roadmap.summary ? fixMojibake(roadmap.summary) : undefined}
        actions={
          <span className="inline-flex items-center gap-2 rounded-[7px] border border-rule bg-paper px-3 py-1.5 text-[12px] text-ink-2">
            <span className="h-2 w-2 rounded-full bg-green" aria-hidden="true" />
            {Math.round(roadmap.confidence * 100)}% confidence
          </span>
        }
      />

      {/* Overall progress */}
      <div className="mb-7 grid gap-4 rounded-[12px] border border-rule bg-paper p-6 sm:grid-cols-[1fr_auto] sm:items-center">
        <div className="min-w-0">
          <p className="mb-1 text-[12px] font-semibold uppercase tracking-[0.1em] text-ink-3">
            Overall progress
          </p>
          <RoadmapProgressBar value={overallPct} showValue={false} />
        </div>
        <div className="flex gap-7 sm:gap-9">
          <div>
            <p className="font-serif text-[22px] font-medium text-ink">
              {completedMilestones}/{totalMilestones}
            </p>
            <p className="text-[11.5px] text-ink-3">milestones</p>
          </div>
          <div>
            <p className="font-serif text-[22px] font-medium text-ink">{phases.length}</p>
            <p className="text-[11.5px] text-ink-3">phases</p>
          </div>
          <div>
            <p className="font-serif text-[22px] font-medium text-ink">{totalWeeks}</p>
            <p className="text-[11.5px] text-ink-3">weeks</p>
          </div>
        </div>
      </div>

      {/* Phase grid */}
      <div className="grid gap-4 md:grid-cols-2">
        {phases.map((phase) => (
          <PhaseCard
            key={phase.id}
            phase={phase}
            status={statuses[phase.id]}
            milestonesDone={doneInPhase(phase.id, phase.milestones.length)}
          />
        ))}
      </div>

      {/* Weekly habits */}
      {roadmap.weeklyHabits.length > 0 && (
        <section className="mt-8">
          <h2 className="mb-3.5 font-serif text-[18px] font-medium tracking-[-0.01em] text-ink">
            Weekly habits
          </h2>
          <div className="grid gap-3 sm:grid-cols-2">
            {roadmap.weeklyHabits.map((habit) => (
              <div
                key={habit.order}
                className="flex items-start gap-3 rounded-[10px] border border-rule bg-paper p-4"
              >
                <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-[7px] bg-green-faint font-mono text-[11px] font-semibold text-green-2">
                  {habit.frequency.slice(0, 3).toUpperCase()}
                </span>
                <div className="min-w-0">
                  <p className="text-[13.5px] font-medium leading-snug text-ink">{habit.text}</p>
                  {habit.rationale && (
                    <p className="mt-0.5 text-[12px] leading-snug text-ink-3">{habit.rationale}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
