export const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export const WS_URL = process.env.NEXT_PUBLIC_WS_URL ?? "ws://localhost:8000/ws";

export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  roadmap: "/roadmap",
  roadmapGenerate: "/roadmap/generate",
  roadmapOptions: "/roadmap-options",
  skillGraph: "/skill-graph",
  cvAnalysis: "/cv-analysis",
  discovery: "/discovery",
  coach: "/coach",
  market: "/market",
  localisation: "/localisation",
  autopilot: "/autopilot",
  careerTwin: "/career-twin",
  analytics: "/analytics",
  progress: "/progress",
  healthMethodology: "/progress/methodology",
  schedule: "/schedule",
  networking: "/networking",
  opportunities: "/opportunities",
  monthlyPlan: "/monthly-plan",
  books: "/books",
  evidence: "/evidence",
  credentials: "/credentials",
  verify: (token: string) => `/verify/${token}`,
  learning: "/learning",
  cohorts: "/cohorts",
  cohort: (id: string) => `/cohorts/${id}`,
  mentorship: "/mentorship",
  negotiation: "/negotiation",
  interview: "/interview",
  outreach: "/outreach",
  wellness: "/wellness",
  oss: "/open-source",
  storytelling: "/storytelling",
  applications: "/applications",
  application: (id: string) => `/applications/${id}`,
  portfolio: "/portfolio",
  newsletter: "/newsletter",
  help: "/help",
  settings: "/settings",
  settingsProfile: "/settings/profile",
  settingsIntegrations: "/settings/integrations",
  settingsBilling: "/settings/billing",
  developer: "/developer",
  privacy: "/settings/privacy",
} as const;

export const QUERY_KEYS = {
  me: ["user", "me"] as const,
  roadmap: (id?: string) => ["roadmap", id] as const,
  roadmapProgress: (id: string) => ["roadmap", id, "progress"] as const,
  roadmapList: ["roadmap", "list"] as const,
  roadmapListInfinite: ["roadmap", "list", "infinite"] as const,
  notifications: ["notifications"] as const,
  market: ["market"] as const,
  marketOverview: ["market", "overview"] as const,
  session: ["session"] as const,
  opportunityAlerts: ["opportunity", "alerts"] as const,
  books: ["books"] as const,
  book: (id: string) => ["books", id] as const,
  habits: ["schedule", "habits"] as const,
  scheduleBlocks: ["schedule", "blocks"] as const,
  scheduleBudget: ["schedule", "budget"] as const,
  scheduleTimeLogs: ["schedule", "time-logs"] as const,
  contacts: ["networking", "contacts"] as const,
  networkingEvents: ["networking", "events"] as const,
  outreach: ["networking", "outreach"] as const,
  weeklyReviews: ["progress", "reviews"] as const,
  health: ["progress", "health"] as const,
  monthlyPlans: ["monthly-plans"] as const,
  monthlyPlan: (id: string) => ["monthly-plans", id] as const,
  integrations: ["integrations"] as const,
  evidence: ["evidence"] as const,
  credentials: ["credentials"] as const,
  learning: ["learning"] as const,
  learningSummary: ["learning", "summary"] as const,
  cohorts: ["cohorts"] as const,
  cohortsDiscover: ["cohorts", "discover"] as const,
  cohort: (id: string) => ["cohorts", id] as const,
  mentorProfile: ["mentorship", "profile"] as const,
  mentors: ["mentorship", "mentors"] as const,
  mentorSessions: ["mentorship", "sessions"] as const,
  caseStudies: ["mentorship", "case-studies"] as const,
  negotiationOffers: ["negotiation", "offers"] as const,
  interviewSessions: ["interview", "sessions"] as const,
  outreachDrafts: ["outreach", "drafts"] as const,
  analytics: ["analytics", "overview"] as const,
  wellnessStatus: ["wellness", "status"] as const,
  wellnessCheckins: ["wellness", "checkins"] as const,
  ossSearch: (language: string, query: string) => ["oss", "search", language, query] as const,
  ossBookmarks: ["oss", "bookmarks"] as const,
  storyDrafts: ["storytelling", "drafts"] as const,
  applications: ["applications"] as const,
  applicationsSummary: ["applications", "summary"] as const,
  application: (id: string) => ["applications", id] as const,
  roadmapOptions: ["roadmap-options"] as const,
  roadmapSnapshots: (roadmapId: string) => ["roadmap-snapshots", roadmapId] as const,
  twinPersona: ["career-twin", "persona"] as const,
  twinToday: ["career-twin", "today"] as const,
  twinHistory: ["career-twin", "history"] as const,
  portfolio: ["portfolio"] as const,
  portfolioPlan: ["portfolio", "plan"] as const,
  apiKeys: ["api-keys"] as const,
  pushConfig: ["push", "config"] as const,
  webhooks: ["webhooks"] as const,
  feedback: ["feedback"] as const,
  newsletter: ["newsletter"] as const,
  newsletterDigest: ["newsletter", "digest"] as const,
  subscription: ["billing", "subscription"] as const,
  discovery: ["discovery"] as const,
  localisation: (country: string, role?: string) =>
    ["localisation", country, role ?? ""] as const,
  localisationSaved: ["localisation", "saved"] as const,
  autopilot: ["autopilot"] as const,
} as const;
